version: '3.9'

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      DB_URL: "mysql://root:password@db:3306/road-trip"
      PORT: "5000"
      TOKEN_SECRET: "mysecrettoken"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: road-trip
    ports:
      - "3310:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
