name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install dependencies
      run: npm install
      working-directory: ./server
    - name: Build
      run: npm run build
      working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.7
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ec2-107-20-101-79.compute-1.amazonaws.com
        REMOTE_USER: ubuntu
        TARGET: /home/ubuntu/road-trip
