name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install dependencies
      run: npm install
      working-directory: ./server
    - name: Build
      run: npm run build
      working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.7
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
        server: ec2-107-20-101-79.compute-1.amazonaws.com
        username: ubuntu
        remote_path: /home/ubuntu
        local_path: ./server
        script: |
          cd /home/ubuntu
          pm2 restart ecosystem.config.js
